import re
from typing import TypeVar

from openai import OpenAI
from pydantic import BaseModel, Field, field_validator

from .config import settings

T = TypeVar("T", bound=BaseModel)


def _parse_json_response(raw: str, model: type[T]) -> T:
    """Strip markdown fences and parse JSON into a Pydantic model."""
    cleaned = raw.strip()
    # Remove ```json or ``` fences
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    return model.model_validate_json(cleaned)

MASTODON_MAX_CHARS = 475  # Reserve 25 chars for "\n\nPost generated by AI."


class MastodonPostContent(BaseModel):
    """Validated Mastodon post content."""

    content: str = Field(
        ...,
        description="The post content for Mastodon, max 475 characters",
    )
    hashtags: list[str] = Field(
        default_factory=list,
        description="Relevant hashtags (without # prefix)",
    )

    @field_validator("content")
    @classmethod
    def validate_content_length(cls, v: str) -> str:
        """Ensure content doesn't exceed Mastodon's character limit."""
        v = v.strip()
        if len(v) > MASTODON_MAX_CHARS:
            # Truncate intelligently at word boundary if possible
            truncated = v[: MASTODON_MAX_CHARS - 3]
            last_space = truncated.rfind(" ")
            if last_space > MASTODON_MAX_CHARS - 50:
                truncated = truncated[:last_space]
            return truncated + "..."
        return v

    def to_post_text(self) -> str:
        """Convert to final post text with hashtags appended."""
        text = self.content
        if self.hashtags:
            hashtag_str = " ".join(f"#{tag.lstrip('#')}" for tag in self.hashtags)
            combined = f"{text}\n\n{hashtag_str}"
            # Ensure combined doesn't exceed limit
            if len(combined) <= MASTODON_MAX_CHARS:
                return combined
        return text


class MastodonReplyContent(BaseModel):
    """Validated Mastodon reply content."""

    content: str = Field(
        ...,
        description="The reply content for Mastodon, max 475 characters",
    )

    @field_validator("content")
    @classmethod
    def validate_content_length(cls, v: str) -> str:
        """Ensure content doesn't exceed Mastodon's character limit."""
        v = v.strip()
        if len(v) > MASTODON_MAX_CHARS:
            truncated = v[: MASTODON_MAX_CHARS - 3]
            last_space = truncated.rfind(" ")
            if last_space > MASTODON_MAX_CHARS - 50:
                truncated = truncated[:last_space]
            return truncated + "..."
        return v


def _get_client() -> OpenAI:
    """Get OpenAI client configured for OpenRouter."""
    return OpenAI(
        api_key=settings.openrouter_api_key,
        base_url=settings.openrouter_base_url,
    )


def generate_post(business_context: str, page_content: str, page_title: str) -> str:
    """
    Generate a Mastodon post based on Notion page content.

    Args:
        business_context: The business description from the parent Notion page
        page_content: The content of the updated child page
        page_title: The title of the updated child page

    Returns:
        Generated post text (max 500 chars), validated by Pydantic
    """
    client = _get_client()

    system_prompt = """You are a social media manager creating Mastodon posts.
        Your posts should be:
        - Engaging and authentic
        - Concise (the main content should be under 400 characters to leave room for hashtags)
        - Written in a natural, human voice
        - Based on the business context and page content provided

        Do NOT use excessive emojis or sound overly promotional. Be genuine.

        You MUST respond with valid JSON in this exact format:
        {
        "content": "Your post text here (under 400 chars)",
        "hashtags": ["tag1", "tag2", "tag3"]
        }

        Provide 1-3 relevant hashtags without the # prefix."""

    user_prompt = f"""Business Description:
        {business_context}

        ---

        Page Title: {page_title}

        Page Content:
        {page_content}

        ---

        Write a Mastodon post for the described account, based on the page title and content. Respond with JSON only."""

    response = client.responses.create(
        model=settings.openrouter_model,
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )

    post = _parse_json_response(response.output_text, MastodonPostContent)
    return post.to_post_text()


def generate_reply(
    post_content: str,
    post_author: str,
    business_context: str,
) -> str:
    """
    Generate a human, supportive reply to a Mastodon post.

    Args:
        post_content: The content of the post to reply to
        post_author: The author's display name or handle
        business_context: Business description for tone/context (not for promotion)

    Returns:
        Generated reply text, validated by Pydantic
    """
    client = _get_client()

    system_prompt = """You are writing a reply to a Mastodon post. Your reply should be:
        - Human, warm, and genuine
        - Supportive and connective
        - Brief (1-3 sentences typically)
        - NOT promotional at all - do not mention your business or products
        - Engaging with what the person actually said
        - Natural conversation, like a real person would respond

        You're building community and genuine connections, not selling anything.
        Never use corporate speak. Be a real person having a real conversation.
        Avoid emojis unless the original post clearly uses them.
        Do not include hashtags.

        You MUST respond with valid JSON in this exact format:
        {
        "content": "Your reply text here"
        }

        Just the reply text, nothing else."""

    user_prompt = f"""Your business context (for understanding your perspective, NOT for promotion):
        {business_context}

        ---

        Post by {post_author}:
        "{post_content}"

        ---

        Write a friendly, genuine reply."""

    response = client.responses.create(
        model=settings.openrouter_model,
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )

    parsed = _parse_json_response(response.output_text, MastodonReplyContent)
    return parsed.content
